# Config for multi-device full finetuning in full_finetune_distributed.py
# using a Mistral 7B model
#
# This config uses hyperparameters based on small set of experiments and information
# available on various forums. These are not meant to replicate the numbers
# from the paper
#
# This config assumes that you've run the following command before launching
# this run:
#   tune download mistralai/Mixtral-8x7B-v0.1 --output-dir /tmp/Mixtral-8x7B-v0.1
#
# Run this config on 4 GPUs using the following:
#   tune run --nnodes 1 --nproc_per_node 4 full_finetune_distributed --config mixtral/8x7B_full
#
# You can add specific overrides through the command line. For example
# to override the checkpointer directory while launching training
# you can run:
#   tune run --nnodes 1 --nproc_per_node 4 full_finetune_distributed --config mixtral/8x7B_full checkpointer.checkpoint_dir=<YOUR_CHECKPOINT_DIR>
#
# This config works best when the model is being fine-tuned on 2+ GPUs.

# Tokenizer
tokenizer:
  _component_: torchtune.models.mixtral.mixtral_tokenizer
  path: /tmp/Mixtral-8x7B-v0.1/tokenizer.model

# Dataset
dataset:
  _component_: torchtune.datasets.alpaca_dataset
  train_on_input: True
seed: null
shuffle: True

# Model Arguments
model:
  _component_: torchtune.models.mixtral.mixtral_8x7b

checkpointer:
  _component_: torchtune.utils.FullModelHFCheckpointer
  checkpoint_dir: /tmp/Mixtral-8x7B-v0.1
  checkpoint_files: [
    consolidated.01.pt,
    consolidated.02.pt,
    consolidated.03.pt,
    consolidated.04.pt,
    consolidated.05.pt,
    consolidated.06.pt,
    consolidated.07.pt,
  ]
  recipe_checkpoint: null
  output_dir: /tmp/Mixtral-8x7B-v0.1/
  model_type: MIXTRAL
resume_from_checkpoint: False

# Fine-tuning arguments
batch_size: 2
epochs: 3
optimizer:
  _component_: torch.optim.AdamW
  lr: 5e-6
loss:
  _component_: torch.nn.CrossEntropyLoss
max_steps_per_epoch: null
gradient_accumulation_steps: 1


# Training env
device: cuda

# Memory management
enable_activation_checkpointing: True

# Reduced precision
dtype: bf16

# Logging
metric_logger:
  _component_: torchtune.utils.metric_logging.DiskLogger
  log_dir: ${output_dir}
output_dir: /tmp/Mixtral-8x7B-v0.1/
log_every_n_steps: null
